apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: poller
  labels:
    app: poller
spec:
  # Every Monday at 12AM
  #doesn't matter
  #schedule: "0 12 * * 1"
  schedule: "*/15 * * * *"
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 1200
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          enableServiceLinks: false
          automountServiceAccountToken: false
          securityContext:
            runAsGroup: 100001
            runAsNonRoot: true
            runAsUser: 100001
          containers:
          - name: poller-cron
            image: ${REPOSITORY_BASE_URL}/crossnokaye/carbon/poller:${VERSION}
            args:
              - "-agent-addr=grafana-agent-deployment.monitoring.svc.cluster.local.:4317"
            env:
              - name: CLICKHOUSE_ADDR
                value: "${CLICKHOUSE_ADDR}"
              - name: CLICKHOUSE_USER
                value: "${CLICKHOUSE_USER}"
              - name: CLICKHOUSE_PASSWORD
                value: "${CLICKHOUSE_PASSWORD}"
              - name: CLICKHOUSE_SSL
                value: "${CLICKHOUSE_SSL}"
              - name: SINGULARITY_API_KEY
                value: "${SINGULARITY_API_KEY}"
            securityContext:
              readOnlyRootFilesystem: true
            resources:
              requests:
                memory: "100Mi"
                cpu: "10m"
              limits:
                memory: "100Mi"
                cpu: "10m"