apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: carbon

resources:
  - ./rbac.yaml
  - ./synced-secret.yaml
  - ./cronjob.yaml

commonAnnotations:
  crossnokaye.com/carbon-poller-version: ${VERSION}
  