apiVersion: v1
kind: Service
metadata:
  name: poller
  labels:
    app: poller
spec:
  type: ClusterIP
  ports:
   - name: grpc
     targetPort: 12500
     port: 12500
   - name: http-metrics
     targetPort: 12501
     port: 12501
  selector:
    app: poller