apiVersion: v1
kind: Service
metadata:
  name: calc
  labels:
    app: calc
spec:
  type: ClusterIP
  ports:
   - name: grpc
     targetPort: 12200
     port: 12200
   - name: http-metrics
     targetPort: 12201
     port: 12201
  selector:
    app: calc