---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  crossnokaye.com/repository: carbon

resources:
  - ./namespace.yaml
  - ./synced-secret.yaml
  - ./poller/
  - ./calc/

