// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	poller "github.com/crossnokaye/carbon/services/poller/gen/poller"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetEmissions provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *Client) GetEmissions(_a0 context.Context, _a1 string, _a2 string, _a3 string, _a4 []*poller.CarbonForecast) ([]*poller.CarbonForecast, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	var r0 []*poller.CarbonForecast
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []*poller.CarbonForecast) []*poller.CarbonForecast); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*poller.CarbonForecast)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, []*poller.CarbonForecast) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClient(t mockConstructorTestingTNewClient) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
