#!/usr/bin/env bash

set -e

echo "Starting services..."

GIT_ROOT=$(git rev-parse --show-toplevel)
pushd ${GIT_ROOT}

source .env
source ./scripts/utils/common.sh

if grep -qEi "(Microsoft|WSL)" /proc/version &> /dev/null ; then
    export HOST_GATEWAY=$(hostname -I)
else
    export HOST_GATEWAY='host-gateway'
fi

docker-compose -f docker-compose/docker-compose-grafana.yml up -d --remove-orphans 

./scripts/start_databases
overmind start
#used to read environment variables from a file and use them as parameters to configure overmind per directory
popd