name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

env:
  GOPRIVATE: "github.com/crossnokaye/*"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.ROBOT_TOKEN }}
        run: git config --global url."https://crossnokaye-robot:${TOKEN}@github.com".insteadOf "https://github.com"
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-v1-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-v1-
      - name: tests
        run: "true"